### ISSUE TITLE
Specify the path of the dvm config file to get the dart version

### ISSUE THREAD

**Issue by morikann** [blendfactory/dvm-config-action#9]
Thank you for creating a great tool! I love using it every day.

Let me suggest one additional feature.
If you don't need it, you could close it.

### Suggestion
As stated in the title of the issue, it would be nice to be able to specify the path of the file from which the dvm version is obtained.
I imagine the following in flutter-fvm-config-action.

<img width="866" alt="スクリーンショット 2024-03-14 8 51 42" src="https://github.com/blendfactory/dvm-config-action/assets/70502790/748ddf1d-c9df-4ba6-8cd9-1674eec7658b">

**Comment by blendthink** [comment]
@morikann 
I implemented the following pull request and released it in 2.0.0!
https://github.com/blendfactory/dvm-config-action/pull/10
